apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: python
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 5000
  type: NodePort

