name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Terraform/**'
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  terraform-plan:
    if: github.event_name == 'pull_request' && github.head_ref != 'main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./Terraform
        id: plan
        run: terraform plan -input=false -no-color > plan.out

      - name: Save plan output
        run: cat Terraform/plan.out

      - name: Comment PR with plan output
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          header: terraform plan result
          message: |
            ```
            ${{ steps.plan.outputs.stdout || steps.plan.outputs.plan }}
            ```
  
  terraform-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ./Terraform
        run: terraform apply -input=false -auto-approve

