apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2025-02-28T09:14:20Z","labels":{"app.kubernetes.io/instance":"nginx","component":"apiserver","provider":"kubernetes"},"name":"kubernetes","namespace":"default","resourceVersion":"16911","uid":"ab3a6ad7-2919-423d-a4dd-9e228228517b"},"spec":{"clusterIP":"10.43.0.1","clusterIPs":["10.43.0.1"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"https","port":443,"protocol":"TCP","targetPort":6443}],"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2025-02-28T09:14:20Z"
  labels:
    app.kubernetes.io/instance: nginx
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "23961"
  uid: ab3a6ad7-2919-423d-a4dd-9e228228517b
spec:
  clusterIP: 10.43.0.1
  clusterIPs:
  - 10.43.0.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
