apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2025-02-28T09:14:20Z","labels":{"app.kubernetes.io/instance":"nginx","component":"apiserver","provider":"kubernetes"},"name":"kubernetes","namespace":"default","resourceVersion":"195","uid":"ab3a6ad7-2919-423d-a4dd-9e228228517b"},"spec":{"clusterIP":"10.43.0.1","clusterIPs":["10.43.0.1"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"https","port":443,"protocol":"TCP","targetPort":6443}],"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    creationTimestamp: "2025-02-28T09:14:20Z"
    labels:
      app.kubernetes.io/instance: nginx
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "16911"
    uid: ab3a6ad7-2919-423d-a4dd-9e228228517b
  spec:
    clusterIP: 10.43.0.1
    clusterIPs:
    - 10.43.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2025-03-03T07:33:24Z","labels":{"app":"app1","app.kubernetes.io/instance":"nginx"},"name":"svc1","namespace":"default","resourceVersion":"16910","uid":"a4cd0eef-50b5-4ffe-9724-4e40e7524a46"},"spec":{"clusterIP":"10.43.233.251","clusterIPs":["10.43.233.251"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":31612,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"app1"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
    creationTimestamp: "2025-03-03T07:33:24Z"
    labels:
      app: app1
      app.kubernetes.io/instance: nginx
    name: svc1
    namespace: default
    resourceVersion: "23499"
    uid: a4cd0eef-50b5-4ffe-9724-4e40e7524a46
  spec:
    clusterIP: 10.43.233.251
    clusterIPs:
    - 10.43.233.251
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31612
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: app1
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
