apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: app1
    app.kubernetes.io/instance: nginx
  name: svc1
  namespace: default
spec:
  clusterIP: 10.43.233.251
  clusterIPs:
  - 10.43.233.251
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31612
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
