name: Check terraform version
on:
 workflow_dispatch:
jobs:
  Check-tf-version:
    name: Check tf version
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Debug runner environment minimal
        shell: bash
        run: |
          echo "User: $USER"
          echo "PATH: $PATH"
          echo "Check terraform binary existence"
          if [ -x /usr/local/bin/terraform ]; then
            echo "Terraform binary found and executable"
          else
            echo "Terraform binary not found or not executable"
          fi
          echo "Run terraform version"
          /usr/local/bin/terraform version || echo "Failed to run terraform version"
      - name: Debug - check terraform access
        run: |
           id
           ls -l /usr/local/bin/terraform
           /usr/local/bin/terraform version
        env:
           PATH: /usr/local/bin:$PATH
      - name: Check tf version
        run: /usr/local/bin/terraform version