name: Check terraform version
on:
 workflow_dispatch:
jobs:
  Check-tf-version:
    name: Check tf version
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check bash availability
        run: |
          if command -v bash; then
            echo "bash is available"
          else
            echo "bash is NOT available"
          fi
      - name: Debug - check terraform access
        run: |
           id
           ls -l /usr/local/bin/terraform
           /usr/local/bin/terraform version
        env:
           PATH: /usr/local/bin:$PATH
      - name: Check tf version
        run: /usr/local/bin/terraform version