name: Test pipeline for terraform
on:
  workflow_dispatch:
    inputs:
      dir_name:
        description: Enter the name of the dir 
        required: true
      tf_apply:
        description: terraform apply needed?
        required: true
        default: no
        options:
         - yes
         - no
jobs:
  terraform plan:
    name: tf plan 
    runs-on: self-hosted
    steps:
     name: Checkout
     uses: actions/checkout@v3

     name: Go to directory
     run: |
        cd Terraform/{{ inputs.dir_name }}
        terraform init
        terraform plan 
  terraform apply:
    name: tf apply
    runs-on: self-hosted
    if: github.event.inputs.tf_apply == 'yes'

    steps:
      name: Checkout
      uses: actions/checkout@v3

      name: Go dir and apply
      run: |
         cd Terraform/{{ inputs.dir_name }}
         terraform init
         terraform plan
         terraform apply
      
         
     

    
 
  
  

