name: Check terraform version
on:
 workflow_dispatch:
jobs:
  Check-tf-version:
    name: Check tf version
    runs-on: [self-hosted,docker-runner-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check tf version
        run: terraform version