name: Check terraform version
on:
 workflow_dispatch:
jobs:
  Check-tf-version:
    name: Check tf version
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip
      - name: Install Terraform dynamically
        shell: bash
        run: |
          TF_VERSION="1.9.7"
          curl -Lo terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_arm64.zip
          unzip terraform.zip
          chmod +x terraform
          mkdir -p $HOME/bin
          mv terraform $HOME/bin/
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Check tf version
        run: /usr/local/bin/terraform version